package com.example.moviesapi.models.movie

import kotlinx.serialization.SerialInfo
import kotlinx.serialization.Serializable

@Serializable
data class MovieDTO(
    val ageRating: Int?,
    val alternativeName: String? = null,
    val audience: List<Audience>? = null,
    val backdrop: Backdrop? = null,
    val budget: Budget? = null,
    val countries: List<Country>? = null,
    val createdAt: String? = null,
    val description: String?,
    val enName: String? = null,
    val externalId: ExternalId? = null,
    val facts: List<Fact>? = null,
    val fees: Fees? = null,
    val genres: List<Genre>? = null,
    val id: Int,
    val isSeries: Boolean,
    val lists: List<String>? = null,
    val logo: Logo? = null,
    val movieLength: Int?,
    val name: String?,
    val names: List<Name>? = null,
    val networks: Networks? = null,
    val persons: List<Person>? = null,
    val poster: Poster? = null,
    val premiere: Premiere? = null,
    val rating: Rating?,
    val ratingMpaa: String?,
    val releaseYears: List<ReleaseYear>? = null,
    val reviewInfo: ReviewInfo? = null,
    val seasonsInfo: List<SeasonsInfo>? = null,
    val sequelsAndPrequels: List<SequelsAndPrequel>? = null,
    val seriesLength: Int?,
    val shortDescription: String?,
    val similarMovies: List<SimilarMovy>? = null,
    val slogan: String? = null,
    val status: String?,
    val ticketsOnSale: Boolean,
    val top10: Int?,
    val top250: Int?,
    val totalSeriesLength: Int?,
    val type: String,
    val typeNumber: Int,
    val updatedAt: String? = null,
    val videos: Videos? = null,
    val votes: Votes,
    val watchability: Watchability? = null,
    val year: Int? = null,
    //val internalNames: String? = null
)